apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: kitchen
  name: kitchen
spec:
  replicas: {{ .Values.kitchen.deployment.replicas }}
  selector:
    matchLabels:
      io.kompose.service: kitchen
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: kitchen
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: kitchen-config
          - secretRef:
              name: postgres-db-creds
          image: {{ .Values.kitchen.deployment.image }}
          name: kitchen
          resources:
            requests:
              cpu: {{ .Values.kitchen.deployment.resources.requests.cpu }}
              memory: {{ .Values.kitchen.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kitchen.deployment.resources.limits.cpu }}
              memory: {{ .Values.kitchen.deployment.resources.limits.memory }}
      restartPolicy: Always
