apiVersion: v1
kind: ConfigMap
metadata:
  name: web-frontend-config
data:
  REVERSE_PROXY_URL: 'http://127.0.0.1:5000'

  # REVERSE_PROXY_URL: 'https://opswat.chucthien.click/proxy'
  WEB_PORT: '8888'

