apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: web-frontend
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Mean 1 pod can be unavailable during the update
      maxSurge: 1 # Mean 1 pod can be created during the update

  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: web-frontend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: web-frontend-config
            - secretRef:
                name: postgres-db-creds

          image: chucthien03/go-coffeeshop-web
          name: web
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always

