apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    io.kompose.service: counter
spec:
  replicas: {{ .Values.counter.deployment.replicas }}
  selector:
    matchLabels:
      io.kompose.service: counter
  template:
    metadata:
      labels:
        io.kompose.service: counter
    spec:
      containers:
        - name: counter
          image: {{ .Values.counter.deployment.image }}
          resources:
            requests:
              cpu: {{ .Values.counter.deployment.resources.requests.cpu }}
              memory: {{ .Values.counter.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.counter.deployment.resources.limits.cpu }}
              memory: {{ .Values.counter.deployment.resources.limits.memory }}
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: counter-config
            - secretRef:
                name: postgres-db-creds
      restartPolicy: Always
