apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    io.kompose.service: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counter
  template:
    metadata:
      labels:
        io.kompose.service: counter
    spec:
      containers:
        - name: counter
          image: chucthien03/go-coffeeshop-counter
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: counter-config
            - secretRef:
                name: postgres-db-creds
      restartPolicy: Always
