apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: barista
  name: barista
spec:
  replicas: {{ .Values.barista.replicas  }}
  selector:
    matchLabels:
      io.kompose.service: barista
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: barista
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: barista-config
            - secretRef:
                name: postgres-db-creds
          image: {{ .Values.barista.image }}
          name: barista
          resources:
            requests:
              cpu: {{ .Values.barista.resources.requests.cpu }}
              memory: {{ .Values.barista.resources.requests.memory }}
            limits:
              cpu: {{ .Values.barista.resources.limits.cpu }}
              memory: {{ .Values.barista.resources.limits.memory }}
      restartPolicy: {{ .Values.barista.restartPolicy }}
