apiVersion: v1
kind: ConfigMap
metadata:
  name: barista-config
data:
  APP_NAME: 'barista-service in docker'
  IN_DOCKER: "true"
  RABBITMQ_URL: {{ .Values.barista.configMap.RABBITMQ_URL }}
  